/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package site.ycsb.db;

public class papyrusJNI {
  public final static native void kv_init();
  public final static native void kv_put(String jarg1, long jarg2, String jarg3, long jarg4);
  public final static native void kv_get(String jarg1, long jarg2, String jarg3, long jarg4);
  public final static native void kv_checkpoint();
  public final static native void kv_finalize();
}
