/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package site.ycsb.db;

public class papyrus {
  public static void kv_init() {
    papyrusJNI.kv_init();
  }

  public static void kv_put(String key, long key_len, String value, long value_len) {
    papyrusJNI.kv_put(key, key_len, value, value_len);
  }

  public static void kv_get(String key, long key_len, String value, long value_len) {
    papyrusJNI.kv_get(key, key_len, value, value_len);
  }

  public static void kv_checkpoint() {
    papyrusJNI.kv_checkpoint();
  }

  public static void kv_finalize() {
    papyrusJNI.kv_finalize();
  }

}
